apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-stagging
  namespace: stagging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
