apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-set
  namespace: argocd
spec:
  generators:
    - matrix:  # ✅ Matrix must be inside an array
        generators:
          # 1️⃣ List Generator - Defines environments
          - list:
              elements:
                - env: staging
                  namespace: staging
                  auto-sync: "true"
                - env: prod
                  namespace: prod
                  auto-sync: "false"

          # 2️⃣ Git Generator - Detects Helm charts dynamically
          - git:
              repoURL: https://github.com/gologolo24/Chart  # Your Helm chart repo
              revision: main
              directories:
                - path: patient-crm/*  # Detects Helm charts inside 'patient-crm/'

  template:
    metadata:
      name: "{{ namespace }}-{{ path.basename | lower | replace '_' '-' }}"  # ✅ Ensure valid app name
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ namespace }}"
      sources:
        - repoURL: https://github.com/gologolo24/Chart  # Helm chart repo
          targetRevision: main
          path: "{{ path }}"  # ✅ Uses dynamically detected chart path
          helm:
            valueFiles:
              - "values/{{ env }}-values.yaml"  # Load environment-specific values

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
