apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-set
  namespace: argocd
spec:
  generators:
    # List Generator - Defines environments
    - list:
        elements:
          - env: staging
            namespace: staging
            revision: main
            auto-sync: "true"
          - env: prod
            namespace: prod
            revision: main
            auto-sync: "false"

    # Git Generator - Automatically detects Helm charts in a Git repository
    - git:
        repoURL: https://github.com/gologolo24/Chart  # Change to your Helm chart repo
        revision: main
        directories:
          - path: patient-crm/*  # Assumes new Helm charts are stored under 'charts/' in Git

  template:
    metadata:
      name: "{{ namespace }}-{{ path.basename }}"  # App name = namespace + chart name
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ namespace }}"
      sources:
        - repoURL: https://github.com/gologolo24/Chart  # Helm chart repo
          targetRevision: "{{ revision }}"
          path: "{{ path.basename }}"  # Uses dynamic chart path
          helm:
            valueFiles:
              - "values/{{ env }}-values.yaml"  # Loads environment-specific values

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
