apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: staging
            namespace: staging
            revision: main
            auto-sync: "true"
          - env: prod
            namespace: prod
            revision: main
            auto-sync: "false"
  template:
    metadata:
      name: "{{ namespace }}"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ namespace }}"
      sources:
        - repoURL: https://github.com/gologolo24/Chart  # Change to your Helm chart repo
          targetRevision: "{{ revision }}"
          path: .
          helm:
            valueFiles:
              - "values/{{ env }}-values.yaml"  # Load env-specific values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
